name: kartvizit_okuyucu
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_ml_kit: ^0.18.0
  google_mlkit_text_recognition: ^0.13.0
  image_cropper: ^6.0.0
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  camera: ^0.11.0
  cupertino_icons: ^1.0.6
  extract: ^0.0.3
  
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/json/isimler.json
    - assets/json/iller.json
  uses-material-design: true
